[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_dapp = "2fdSJQEFJppVTYX7KHfDm1aJo5bg75Yvwohcf4BKfE4G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/franze/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
